### ISSUE TITLE
Can't use interrupt pins on Arduino/Genuino 101

### ISSUE THREAD

**Issue by DaisukeUra** [PaulStoffregen/Encoder#18]
Hi there.

I use this library on my Arduino/Genuino 101.
When only use "change" supported interrupt pins, such as 7&8, Encoder instance looks like doesn't count pulses.
It is properly counting when I use "change" not supported pins.
How I use "change" supported interrupt pins on this library?

Best regards.

**Comment by DaisukeUra** [comment]
I try this code, looks like properly counting.

```
#include <Encoder.h>

Encoder *myEnc;

void setup() {
  Serial.begin(9600);
  Serial.println("Basic Encoder Test:");
  myEnc = new Encoder(7, 8);
}

long oldPosition  = -999;

void loop() {
  long newPosition = myEnc->read();
  if (newPosition != oldPosition) {
    oldPosition = newPosition;
    Serial.println(newPosition);
  }
}
```

I don't know why it works, but my problem was maybe solved.
But I think it remains some problem in the library's code.

**Comment by DaisukeUra** [comment]
I've try this code and it properly works.

```
#include <Encoder.h>

Encoder *myEnc;

void setup() {
  Serial.begin(9600);
  Serial.println("Basic Encoder Test:");
  myEnc = new Encoder(7, 8);
}

long oldPosition  = -999;

void loop() {
  long newPosition = myEnc->read();
  if (newPosition != oldPosition) {
    oldPosition = newPosition;
    Serial.println(newPosition);
  }
}
```

I don't know why it works well.
I think it remains some problem in library's code.

Thanks.

**Comment by PaulStoffregen** [comment]
https://www.arduino.cc/en/Main/ArduinoBoard101

"change is only supported by pins 2, 5, 7, 8, 10, 11, 12, 13"

**Comment by DaisukeUra** [comment]
Thanks.
I know change supported pins.

Why does not the sample code below work?

```

#include <Encoder.h>

Encoder myEnc(7, 8);

void setup() {
  Serial.begin(9600);
  Serial.println("Basic Encoder Test:");
}

long oldPosition  = -999;

void loop() {
  long newPosition = myEnc.read();
  if (newPosition != oldPosition) {
    oldPosition = newPosition;
    Serial.println(newPosition);
  }
}
```

**Comment by DaisukeUra** [comment]
This code is Encoder/examples/Basic/Basic.pde.
