### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by arturkowalczyk** [PaulStoffregen/Encoder#5]
Hi Paul,

I tried use your library in version 1.3 on ESP8266, however I noticed that some defines are missing. The problem was already solved by @acropup. I tested the latest version from the master branch and it works fine with my ESP8266. May I ask you to release a new version so Arduino IDE can index it? It would be very helpful.

Cheers,
Artur

**Comment by PaulStoffregen** [comment]
Done.
