### ISSUE TITLE
Not an issue - but...

### ISSUE THREAD

**Issue by phaleas** [PaulStoffregen/Encoder#54]
I'm using your excellent library with an ESP32 - after doing so with Arduinos before. It seems, that you changed some files (ESP pins/interrupts) within the current version 1.4.1. These changes effect the users of ESP platform heavily, and many of them would not expect changes within a version they've already have. Please build a 1.4.2, so that ESP users get the latest changes - which are important.

I can confirm that the encoder runs like charm on an ESP32 with the latest changes.

**Comment by Patrick-Thomas** [comment]
Yes I second this, please release a 1.4.2 version with the latest changes so we can import a ESP32 compatible version easily into Arduino and platformio

**Comment by PaulStoffregen** [comment]
Done
https://github.com/PaulStoffregen/Encoder/releases/tag/1.4.2
