### ISSUE TITLE
Using the encoder lib on an esp8266 via a MCP23017

### ISSUE THREAD

**Issue by brunnwart** [PaulStoffregen/Encoder#9]
Dear Paul,

unfortunately I don't have enough GPIO pins on my esp-07 so I need to use an MCP23017 with the https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library lib.
Do you see a chance to talk to the encoder via the mcp and do you have an idea how this can be done?

With the Adafruit_MCP23017 lib
#include <Wire.h>
#include <Adafruit_MCP23017.h>

I can declare the input pins on the MCP as
mcp.pinMode(x, INPUT);

but I can't do a nested
mcp.Encoder  encmotor1(0, 1); 
to tell that the interrupts are on the MCP.

Do you have a hint for me?

Thanks and regards, Ditmar

**Comment by PaulStoffregen** [comment]
> Do you see a chance to talk to the encoder via the mcp 

Nope, sorry.
